[package]
name = "openfiat-advertisements"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Advertisement publication and matching."
repository = "https://github.com/OpenFiat-org/openfiat-core"

[dependencies]
openfiat-types = { path = "../types" }
openfiat-trade = { path = "../trade" }
