//! The encryption key derivation, checked against the TypeScript SDK
//! rather than against itself.
//!
//! Every assertion in `crates/crypto/src/encryption_key.rs` is a round
//! trip, and a round trip proves nothing about the other implementation:
//! two that are each internally consistent and mutually incompatible both
//! pass one. Here that failure would be silent and expensive — a user
//! enrols in a browser under one key, a counterparty running a node seals a
//! `KeyGrant` to another, and the trade shows "sealed, unreadable" payment
//! details, which is the bug this whole mechanism was built to remove,
//! wearing the fix's clothes.
//!
//! The vectors below were produced by `@openfiat/sdk`
//! (`typescript/scripts/encryption-key-fixture.ts`, wallet seed `07`
//! repeated 32 times) and are asserted here byte for byte.
//! `typescript/tests/encryption-key.test.ts` holds the mirror image: a box
//! this implementation sealed, opened there.
//!
//! Hard-coded rather than generated by shelling out to Node, unlike
//! `openfiat-sdks`' own `seal_cross_language.rs`. That test lives in a repo
//! that has the TypeScript checkout next to it; this one does not, and a
//! test that silently skips whenever a sibling directory is missing is a
//! test that will be skipping in CI without anyone noticing. A fixed vector
//! cannot skip.
//!
//! If these ever disagree with the TypeScript side, do not "fix" either to
//! match the other without deciding which moved: `DERIVATION_MESSAGE` is a
//! wire format, and changing it orphans every key already published to the
//! network.

use openfiat_crypto::{DERIVATION_MESSAGE, EncryptionKeypair, Keypair, SealedBox};

const WALLET_SEED: [u8; 32] = [7u8; 32];
const CHANNEL_KEY: &[u8] = b"32 bytes of channel key, roughly";

/// `@openfiat/sdk`'s signature over `DERIVATION_MESSAGE` for that seed.
const TYPESCRIPT_SIGNATURE: [u8; 64] = [
    39, 48, 222, 29, 73, 105, 58, 218, 239, 151, 215, 236, 222, 153, 7, 24, 210, 93, 217, 47, 241,
    108, 51, 87, 25, 20, 129, 6, 241, 203, 45, 253, 60, 123, 161, 182, 98, 106, 23, 238, 81, 79,
    254, 199, 8, 168, 186, 253, 190, 167, 57, 139, 180, 183, 207, 119, 2, 250, 162, 107, 250, 222,
    147, 1,
];

/// The base58 that wallet's `ClaimType::EncryptionKey` claim carries.
const TYPESCRIPT_PUBLIC_KEY: &str = "AZ18KopCSZw3YpzhrFf3zxvNo6FejeCAnHj3FgJSCNGw";

/// A channel key `@openfiat/sdk` sealed to that published key.
fn typescript_grant() -> SealedBox {
    SealedBox {
        ephemeral_public: [
            194, 56, 211, 243, 19, 0, 212, 82, 174, 69, 49, 3, 115, 240, 74, 92, 17, 255, 198, 65,
            217, 141, 18, 5, 96, 68, 40, 47, 253, 54, 69, 65,
        ],
        nonce: [242, 183, 202, 135, 61, 37, 68, 130, 180, 109, 206, 183],
        ciphertext: vec![
            222, 184, 35, 6, 232, 156, 113, 145, 44, 189, 8, 124, 47, 103, 75, 118, 118, 75, 201,
            65, 235, 179, 17, 252, 93, 255, 123, 24, 4, 251, 199, 50, 226, 22, 30, 10, 228, 130,
            54, 186, 198, 86, 204, 162, 105, 151, 111, 20,
        ],
    }
}

fn wallet() -> Keypair {
    Keypair::from_seed(WALLET_SEED)
}

/// This has to be asserted before anything else. If the two sides sign
/// different bytes, every later failure would look like a sealed-box bug
/// and a reader would chase the wrong thing.
#[test]
fn both_implementations_sign_the_same_derivation_message() {
    assert_eq!(
        wallet()
            .sign(DERIVATION_MESSAGE.as_bytes())
            .as_bytes()
            .expect("a signature this crate produced is 64 bytes"),
        TYPESCRIPT_SIGNATURE,
        "the two implementations' DERIVATION_MESSAGE constants have diverged"
    );
}

#[test]
fn both_implementations_derive_the_same_key_from_that_signature() {
    let derived = EncryptionKeypair::from_signature_bytes(&TYPESCRIPT_SIGNATURE);
    assert_eq!(
        derived.public_key().to_string(),
        TYPESCRIPT_PUBLIC_KEY,
        "the two implementations derive different keys, or write the same key down differently"
    );
}

#[test]
fn a_grant_sealed_by_the_typescript_sdk_opens_here() {
    let derived =
        EncryptionKeypair::from_wallet_signature(&wallet().sign(DERIVATION_MESSAGE.as_bytes()))
            .expect("a wallet signature is 64 bytes");
    assert_eq!(
        derived
            .open(&typescript_grant())
            .expect("a grant sealed by @openfiat/sdk must open here"),
        CHANNEL_KEY
    );
}

/// Guards against the way the test above could pass while proving nothing:
/// if opening ignored the recipient key, it would still succeed.
#[test]
fn a_grant_sealed_by_the_typescript_sdk_is_refused_by_another_wallet() {
    let other = Keypair::from_seed([8u8; 32]);
    let eavesdropper =
        EncryptionKeypair::from_wallet_signature(&other.sign(DERIVATION_MESSAGE.as_bytes()))
            .unwrap();
    assert!(
        eavesdropper.open(&typescript_grant()).is_err(),
        "a grant must not open for a wallet it was not addressed to"
    );
}

#[test]
fn tampering_with_a_typescript_grant_is_caught_here() {
    let derived =
        EncryptionKeypair::from_wallet_signature(&wallet().sign(DERIVATION_MESSAGE.as_bytes()))
            .unwrap();
    // Each field is authenticated by a different part of the construction:
    // the ciphertext by the Poly1305 tag, the ephemeral key by being both
    // the AEAD's associated data and an input to the key derivation, the
    // nonce by being derived rather than carried.
    for field in 0usize..3 {
        let mut sealed = typescript_grant();
        match field {
            0 => sealed.ciphertext[0] ^= 0x01,
            1 => sealed.ephemeral_public[0] ^= 0x01,
            _ => sealed.nonce[0] ^= 0x01,
        }
        assert!(
            derived.open(&sealed).is_err(),
            "a tampered grant must fail rather than return garbage (field {field})"
        );
    }
}
