[package]
name = "openfiat-gossip"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Epidemic message propagation across the peer-to-peer network."
repository = "https://github.com/OpenFiat-org/openfiat-core"

[dependencies]
openfiat-network = { path = "../network" }
openfiat-types = { path = "../types" }
