[package]
name = "openfiat-trade"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Trade lifecycle state machine."
repository = "https://github.com/OpenFiat-org/openfiat-core"

[dependencies]
openfiat-types = { path = "../types", version = "0.1.0" }
openfiat-identity = { path = "../identity", version = "0.1.0" }
