[package]
name = "openfiat-registry"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Service discovery/registry for node-provided services."
repository = "https://github.com/OpenFiat-org/openfiat-core"

[dependencies]
openfiat-network = { path = "../network", version = "0.1.0" }
openfiat-types = { path = "../types", version = "0.1.0" }
