[package]
name = "openfiat-api"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "REST/OpenAPI HTTP surface."
repository = "https://github.com/OpenFiat-org/openfiat-core"

[dependencies]
openfiat-types = { path = "../types", version = "0.1.0" }
openfiat-rpc = { path = "../rpc", version = "0.1.0" }
