[package]
name = "openfiat-swqos"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Node reputation and stake-weighted quality of service."
repository = "https://github.com/OpenFiat-org/openfiat-core"

[dependencies]
openfiat-network = { path = "../network" }
openfiat-reputation = { path = "../reputation" }
openfiat-types = { path = "../types" }
